"""Step 4.0: the retrieval plane's front door. A foreign id becomes a tenant.

The other half of the boundary app/gateway.py holds up. The inference plane has
no tenant and must never learn how to get one; this plane cannot do anything
without one, and everything it will serve comes out of a customer's folder. The
two live in separate files so that "which of these may touch storage" is a
question about imports rather than about reading a function.

WHAT ARRIVES, AND FROM WHOM

    POST /api/v1/...
    Authorization: Bearer <service token>      which SYSTEM is calling
    X-Syslab-Tenant: <external id>             which of THEIR customers

Two credentials answering two different questions, and neither can stand in for
the other. The token is the website proving it is the website; the header is
the website naming one of its own tenants. A token alone cannot choose a
tenant, and a header alone cannot get in.

THE SYSTEM COMES FROM THE TOKEN, NEVER FROM A HEADER
    tenant_alias is keyed by (external system, external id), so ids only mean
    anything inside one system's namespace. If a caller could name its own
    system, one system's token would resolve ids in another's, and the key
    would be decoration. config.RETRIEVAL_TOKENS is therefore a mapping from
    token to system rather than the flat set GATEWAY_TOKENS is.

A FOREIGN ID MUST NEVER BECOME A FILESYSTEM PATH
    The sharpest rule in the project, and this file is where it is kept. The
    value in X-Syslab-Tenant is passed to tenancy.resolve_alias as a lookup
    key and to nothing else -- never to context.validate_tenant_id, never to
    config.resolve_in_data_dir, never into an f-string that becomes a path.
    What reaches context.set_tenant is the LOCAL id that came back out of our
    own control plane, generated by tenancy.new_id().

    `../../etc/passwd` and `Acme Ltd` are not rejected here as malformed. They
    are simply ids that nothing has linked, and they get the same 404 as the
    number 12345 -- which is the point. A distinct error for a malformed id
    would tell a stranger which of their guesses had the right shape.

404, NEVER 403
    An unlinked id, an id linked to a disabled tenant, and an id linked to a
    tenant that has since been deleted all answer 404. "That tenant exists but
    is not yours" confirms an id someone guessed, and over enough guesses it
    counts another customer's tenants. app/jobs.py set this precedent and this
    plane inherits it rather than re-deciding it.

THE DEPENDENCY IS ASYNC, AND THAT IS NOT COSMETIC
    FastAPI runs a `def` dependency in one anyio worker thread and a `def`
    endpoint in another, and a ContextVar set in a worker thread is gone before
    the endpoint runs. Measured in Step 1.5, asserted in tests/test_context.py,
    and the reason main.require_auth is an async generator too. Make this sync
    and tenancy silently stops working.

THE ROUTE ADDED AT 4.6 IS A MAPPING ONTO THE WIRE AND NOT A RETRIEVER
    `POST /api/v1/retrieve` arrived at 4.6 on a router that was already mounted
    and already authenticated -- the order Step 2.0 used, where the pipeline
    existed and was proven before its first producer moved behind it. The
    retrieval itself is `retrieve.search()`; the counting is
    `passages.coverage()`; what is left here is the shape on the wire, the
    token budget, and saying out loud what the answer is not. The rest of the
    plane (`GET /api/v1/documents` and friends) is 4.8.
"""

from __future__ import annotations

from fastapi import APIRouter, Body, Depends, HTTPException, Request
from pydantic import BaseModel, Field

from app import config, context, passages, retrieve, tenancy

# The prefix is frozen surface, the same way /v1 is: the website deploys
# separately, so a narrowing here is found by a customer rather than by a test.
# scripts/check_api_compat.py froze it at 4.6, against
# docs/api/retrieval-v1.released.json.
router = APIRouter(prefix="/api/v1", tags=["retrieval"])

TENANT_HEADER = "x-syslab-tenant"


def calling_system(request: Request) -> str | None:
    """Which external system is this token? None means no token we know.

    Constant-time against every configured token rather than a dict lookup, so
    a wrong guess costs the same as a right one and no early return says which
    token index it got closest to. The dict is keyed by token, which would make
    the lookup O(1) and the timing informative; this walks it instead.

    Through config.tokens_equal rather than hmac.compare_digest, which raises
    on a non-ASCII str: one accented letter in a bearer token would otherwise
    be a 500 from a caller who has not authenticated.
    """
    header = request.headers.get("authorization", "")
    candidate = header[7:].strip() if header.lower().startswith("bearer ") else ""
    if not candidate:
        return None
    found: str | None = None
    for token, system in config.RETRIEVAL_TOKENS.items():
        if config.tokens_equal(candidate, token):
            found = system
    return found


async def require_tenant(request: Request):
    """May this request happen, and whose data is it? One function, both answers.

    Deliberately one function, for the reason main.require_auth gives: splitting
    them would allow a request that is authenticated but ownerless, and that is
    the state everything downstream of here refuses to be in.

    The yield is the teardown. The tenant is put back when the response is done,
    so nothing carries into the next request that happens to reuse this thread.
    """
    if not config.RETRIEVAL_TOKENS:
        raise HTTPException(
            503,
            "The retrieval plane has no service tokens configured. Set "
            "RETRIEVAL_TOKENS in .env as system:token pairs, for example "
            "RETRIEVAL_TOKENS=website:<a long random value>. It refuses to "
            "serve rather than serve without knowing who is calling.",
        )

    system = calling_system(request)
    if system is None:
        raise HTTPException(401, "Invalid or missing bearer token.")

    external_id = request.headers.get(TENANT_HEADER)
    if external_id is None or not external_id.strip():
        # 400 and not 404: the header being absent is the caller's own mistake
        # and says nothing about which tenants exist, so there is nothing to
        # withhold and every reason to be clear about it.
        raise HTTPException(
            400,
            "This plane is tenant-scoped and no X-Syslab-Tenant header arrived. "
            "Send the tenant id from your own system; it is linked to one of "
            "ours by the operator.",
        )

    # The one place a foreign id is used, and it is used as a key. Whatever
    # shape it is -- a path, a name with a space, a megabyte of nonsense -- it
    # is a string looked up in a table, and an unlinked one is a 404.
    tenant = tenancy.resolve_alias(system, external_id)
    if tenant is None:
        raise HTTPException(
            404,
            "No such tenant. If this id is new, an operator links it with: "
            "py scripts/tenant.py alias link <system> <their id> <our id>",
        )

    reset = context.set_tenant(tenant["id"])
    try:
        yield
    finally:
        context.reset_tenant(reset)


# --------------------------------------------------------------------------
# POST /api/v1/retrieve  (4.6)
# --------------------------------------------------------------------------

class RetrieveRequest(BaseModel):
    """What a caller may ask for, and the ceilings are the interesting part.

    Every bound here is decision 5.1's instruction expressed as a number --
    *"just tell the customer the information he needs only"* -- because the
    caller has about 12,171 tokens for the WHOLE conversation and a retrieval
    plane that spends them generously is crowding out the conversation it
    exists to serve.

    `k` DEFAULTS LOW. Eight is the number 512-token passages divide the ~4,000
    token retrieval budget into, and it is a default rather than a maximum
    because a caller who knows they want three should be able to say three.

    `budget_tokens` IS RESPECTED RATHER THAN ADVISORY -- see `fit_budget`. The
    ceiling is the model's entire context window, on the grounds that a
    retrieval budget larger than the window it feeds is a number nobody could
    honour; it is deliberately not the 12,171 figure, because that is the
    website's arithmetic about its own prompt and this plane does not get to
    assume it stays true.

    Unknown fields are IGNORED rather than rejected. The freeze in
    scripts/check_api_compat.py forbids narrowing, and `extra="forbid"` would
    be exactly that: the day the website sends a field this version has not
    heard of, it would start getting 422s from a server that could simply have
    answered.
    """

    query: str = Field(min_length=1, max_length=2000)
    k: int = Field(default=8, ge=1, le=50)
    budget_tokens: int = Field(default=4000, ge=1, le=16384)
    # `None` is every source and an empty list is nothing -- passages._scope
    # holds that decision and the reason for it.
    sources: list[str] | None = Field(default=None, max_length=500)


def fit_budget(candidates: list[dict], budget_tokens: int) -> tuple[list[dict], int, bool]:
    """Take passages in rank order until the next one would not fit.

    Returns what fits, what it costs, and whether the budget is what stopped
    it. STRICT, not approximate: a 600-token passage does not go into a
    500-token budget. Handing it over anyway would blow the budget of a caller
    who asked precisely so that would not happen, which makes the field a
    decoration.

    IT STOPS RATHER THAN SKIPPING AHEAD to a smaller passage further down the
    ranking. Skipping would fill the budget more completely and would quietly
    return a worse-ranked set of passages as though it were the best ones; a
    prefix of the ranking is the honest thing, and `truncated` says the budget
    is why it is short.
    """
    kept: list[dict] = []
    spent = 0
    for candidate in candidates:
        if spent + candidate["tokens"] > budget_tokens:
            # True even when NOTHING fit. A first passage larger than the whole
            # budget is the one case where `returned` is 0 while `matched` is
            # not, and `truncated` is what tells those apart from "nothing
            # matched".
            return kept, spent, True
        kept.append(candidate)
        spent += candidate["tokens"]
    return kept, spent, False


def what_this_means(coverage: dict, truncated: bool) -> str:
    """A retrieval result reads like an answer. This says that it is not.

    Carried over in spirit from `search_files`, which already says out loud
    that a text match is not a filter -- and extended with the numbers, because
    decision 5.6's whole argument is that *"8 of 31"* is the difference between
    a wrong aggregate answer nobody can detect and one anybody can.

    Written from the coverage block rather than from a template with the
    numbers pasted in, so a sentence cannot claim a census the counts
    contradict.
    """
    matched, returned = coverage["matched"], coverage["returned"]
    if not matched:
        return (
            "Nothing in this customer's indexed passages matched those words. That is "
            "not evidence the material does not discuss it: a paraphrase of words the "
            "document does not use will not be found by keyword search."
        )
    if not returned:
        return (
            f"{matched} passages matched and NONE were returned, because the first one "
            f"alone is larger than budget_tokens. Raise the budget rather than reading "
            f"this as an empty result."
        )
    census = (
        f"This is a sample, not a census: {returned} of {matched} matching passages "
        f"were returned."
        if returned < matched
        else f"All {matched} matching passages were returned."
    )
    budget = (
        " The token budget, not the supply of passages, is what stopped it."
        if truncated
        else ""
    )
    return (
        "These passages CONTAIN or RESEMBLE the words asked about. "
        f"{census}{budget} Do not answer a question about ALL of something from this: "
        "count and total questions need the extracted fact tables and SQL, not passages."
    )


@router.post("/retrieve", dependencies=[Depends(require_tenant)])
def retrieve_passages(body: RetrieveRequest = Body(...)) -> dict:
    """Which parts of this customer's material bear on this question.

    Passages and never prose -- README.md's boundary rule: this server never
    learns what a conversation is. Query rewriting from the turn before and
    answer synthesis are the website's, because they need the conversation and
    it is not here.

    THE COUNTS COME FROM THE INDEX AND THE RANKING COMES FROM THE SEAM, and
    they are two calls on purpose. `retrieve.search()` returns ranks and no
    scores, so a coverage figure assembled from what it handed back would equal
    `k` every time and would agree with itself every time. `passages.coverage()`
    asks the index instead: two COUNT(*)s against a match it has already done.

    A SOURCE THAT IS NOT THIS TENANT'S FILTERS TO NOTHING AND IS NOT AN ERROR.
    There is nothing to reject: the filter is applied inside the tenant's own
    index, so a name from another tenant matches no row there. Answering "no
    such document" would confirm a filename to whoever guessed it, and the 404
    rule in this module's own header is the same rule. It is not a special
    case in the code, which is why it cannot rot -- but it IS a gated
    property, because "there is no code for it" is an argument and not a check.
    """
    try:
        found = retrieve.search(body.query, body.k, sources=body.sources)
        counts = passages.coverage(body.query, sources=body.sources)
    except retrieve.RetrieverError as exc:
        # 400: the question could not be asked. Distinct from nothing matching,
        # which is a 200 with an empty list and a `what_this_means` that says
        # keyword search cannot match words a document does not use.
        raise HTTPException(400, str(exc)) from exc
    except passages.PassageError as exc:
        raise HTTPException(400, str(exc)) from exc

    resolved = []
    for hit in found["passages"]:
        row = passages.passage(hit.chunk_id)
        # None is a real possibility rather than a defensive flourish: the
        # index can be rebuilt between the ranking and this lookup. Dropping
        # the passage is right -- a citation that cannot be resolved is a
        # decoration -- and `coverage.returned` counts what actually came back,
        # so a drop shows up as a number rather than as a silence.
        if row is None:
            continue
        resolved.append({**row, "found_by": list(hit.found_by)})

    kept, spent, truncated = fit_budget(resolved, body.budget_tokens)

    # Ranks are renumbered over what actually shipped, so they are always
    # 1..len(passages) with no holes. A gap would be a puzzle nobody could
    # solve from the response: it would mean either the budget or a failed
    # lookup, and those are already reported separately and honestly.
    served = [
        {
            "chunk_id": row["chunk_id"],
            "source": row["source"],
            "text": row["text"],
            "start": row["start"],
            "end": row["end"],
            "tokens": row["tokens"],
            "rank": position,
            "found_by": row["found_by"],
        }
        for position, row in enumerate(kept, start=1)
    ]

    coverage = {
        "searched": counts["searched"],
        "matched": counts["matched"],
        "returned": len(served),
    }
    return {
        "query": body.query,
        "retrievers": found["retrievers"],
        # Always present, empty today, and load-bearing the day it is not: a
        # fused list missing the vector side is a worse answer that looks
        # exactly like a normal one. `retrievers` says who answered and this
        # says who could not, with the reason.
        "retrievers_unavailable": found["failed"],
        "passages": served,
        "coverage": coverage,
        "tokens_returned": spent,
        "truncated": truncated,
        "what_this_means": what_this_means(coverage, truncated),
    }
