"""Step 4.0: the retrieval plane's front door. A foreign id becomes a tenant.

The other half of the boundary app/gateway.py holds up. The inference plane has
no tenant and must never learn how to get one; this plane cannot do anything
without one, and everything it will serve comes out of a customer's folder. The
two live in separate files so that "which of these may touch storage" is a
question about imports rather than about reading a function.

WHAT ARRIVES, AND FROM WHOM

    POST /api/v1/...
    Authorization: Bearer <service token>      which SYSTEM is calling
    X-Syslab-Tenant: <external id>             which of THEIR customers

Two credentials answering two different questions, and neither can stand in for
the other. The token is the website proving it is the website; the header is
the website naming one of its own tenants. A token alone cannot choose a
tenant, and a header alone cannot get in.

THE SYSTEM COMES FROM THE TOKEN, NEVER FROM A HEADER
    tenant_alias is keyed by (external system, external id), so ids only mean
    anything inside one system's namespace. If a caller could name its own
    system, one system's token would resolve ids in another's, and the key
    would be decoration. config.RETRIEVAL_TOKENS is therefore a mapping from
    token to system rather than the flat set GATEWAY_TOKENS is.

A FOREIGN ID MUST NEVER BECOME A FILESYSTEM PATH
    The sharpest rule in the project, and this file is where it is kept. The
    value in X-Syslab-Tenant is passed to tenancy.resolve_alias as a lookup
    key and to nothing else -- never to context.validate_tenant_id, never to
    config.resolve_in_data_dir, never into an f-string that becomes a path.
    What reaches context.set_tenant is the LOCAL id that came back out of our
    own control plane, generated by tenancy.new_id().

    `../../etc/passwd` and `Acme Ltd` are not rejected here as malformed. They
    are simply ids that nothing has linked, and they get the same 404 as the
    number 12345 -- which is the point. A distinct error for a malformed id
    would tell a stranger which of their guesses had the right shape.

404, NEVER 403
    An unlinked id, an id linked to a disabled tenant, and an id linked to a
    tenant that has since been deleted all answer 404. "That tenant exists but
    is not yours" confirms an id someone guessed, and over enough guesses it
    counts another customer's tenants. app/jobs.py set this precedent and this
    plane inherits it rather than re-deciding it.

THE DEPENDENCY IS ASYNC, AND THAT IS NOT COSMETIC
    FastAPI runs a `def` dependency in one anyio worker thread and a `def`
    endpoint in another, and a ContextVar set in a worker thread is gone before
    the endpoint runs. Measured in Step 1.5, asserted in tests/test_context.py,
    and the reason main.require_auth is an async generator too. Make this sync
    and tenancy silently stops working.

THE ROUTER IS EMPTY ON PURPOSE
    Step 4.0 is the bridge, not the endpoints. `POST /api/v1/retrieve` arrives
    in 4.5 and the rest of the plane in 4.6, and they arrive as routes on a
    router that is already mounted and already authenticated. Same order Step
    2.0 used: the pipeline existed and was proven before its first producer
    moved behind it.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Request

from app import config, context, tenancy

# The prefix is frozen surface, the same way /v1 is: the website deploys
# separately, so a narrowing here is found by a customer rather than by a test.
# scripts/check_api_compat.py takes it over in 4.6, once there are routes to
# freeze.
router = APIRouter(prefix="/api/v1", tags=["retrieval"])

TENANT_HEADER = "x-syslab-tenant"


def calling_system(request: Request) -> str | None:
    """Which external system is this token? None means no token we know.

    Constant-time against every configured token rather than a dict lookup, so
    a wrong guess costs the same as a right one and no early return says which
    token index it got closest to. The dict is keyed by token, which would make
    the lookup O(1) and the timing informative; this walks it instead.

    Through config.tokens_equal rather than hmac.compare_digest, which raises
    on a non-ASCII str: one accented letter in a bearer token would otherwise
    be a 500 from a caller who has not authenticated.
    """
    header = request.headers.get("authorization", "")
    candidate = header[7:].strip() if header.lower().startswith("bearer ") else ""
    if not candidate:
        return None
    found: str | None = None
    for token, system in config.RETRIEVAL_TOKENS.items():
        if config.tokens_equal(candidate, token):
            found = system
    return found


async def require_tenant(request: Request):
    """May this request happen, and whose data is it? One function, both answers.

    Deliberately one function, for the reason main.require_auth gives: splitting
    them would allow a request that is authenticated but ownerless, and that is
    the state everything downstream of here refuses to be in.

    The yield is the teardown. The tenant is put back when the response is done,
    so nothing carries into the next request that happens to reuse this thread.
    """
    if not config.RETRIEVAL_TOKENS:
        raise HTTPException(
            503,
            "The retrieval plane has no service tokens configured. Set "
            "RETRIEVAL_TOKENS in .env as system:token pairs, for example "
            "RETRIEVAL_TOKENS=website:<a long random value>. It refuses to "
            "serve rather than serve without knowing who is calling.",
        )

    system = calling_system(request)
    if system is None:
        raise HTTPException(401, "Invalid or missing bearer token.")

    external_id = request.headers.get(TENANT_HEADER)
    if external_id is None or not external_id.strip():
        # 400 and not 404: the header being absent is the caller's own mistake
        # and says nothing about which tenants exist, so there is nothing to
        # withhold and every reason to be clear about it.
        raise HTTPException(
            400,
            "This plane is tenant-scoped and no X-Syslab-Tenant header arrived. "
            "Send the tenant id from your own system; it is linked to one of "
            "ours by the operator.",
        )

    # The one place a foreign id is used, and it is used as a key. Whatever
    # shape it is -- a path, a name with a space, a megabyte of nonsense -- it
    # is a string looked up in a table, and an unlinked one is a 404.
    tenant = tenancy.resolve_alias(system, external_id)
    if tenant is None:
        raise HTTPException(
            404,
            "No such tenant. If this id is new, an operator links it with: "
            "py scripts/tenant.py alias link <system> <their id> <our id>",
        )

    reset = context.set_tenant(tenant["id"])
    try:
        yield
    finally:
        context.reset_tenant(reset)
