"""Phase 02 gate: exercise every tool function on real files, with no model involved.

Writes its scratch files into DATA_DIR and leaves them there so you can open
them in Excel and a PDF viewer and judge them yourself.

    py scripts/check_tools.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _deps import require  # noqa: E402

require("pymupdf", "openpyxl", "reportlab")

from app import tools  # noqa: E402
from app import context  # noqa: E402
from app.config import BOOTSTRAP_TENANT, data_dir, ensure_data_dir  # noqa: E402

LINE = "-" * 62
PDF_NAME = "phase02_sample.pdf"
XLSX_NAME = "phase02_sample.xlsx"

passed: list[str] = []
failed: list[str] = []


def step(name: str) -> None:
    print(f"\n{name}\n{LINE}")


def ok(name: str, detail: str = "") -> None:
    passed.append(name)
    print(f"  PASS  {name}{'  ' + detail if detail else ''}")


def bad(name: str, detail: str) -> None:
    failed.append(name)
    print(f"  FAIL  {name}: {detail}")


def check(name: str, condition: bool, detail: str = "") -> None:
    ok(name, detail) if condition else bad(name, detail or "condition not met")


def main() -> int:
    ensure_data_dir()
    print("\nsyslab-server / Phase 02 tool check")
    print(f"Data folder: {data_dir()}")

    # ---- write_pdf ----------------------------------------------------
    step("write_pdf")
    try:
        result = tools.write_pdf(
            PDF_NAME,
            title="Phase 02 Sample Document",
            body=(
                "This file was generated by the Phase 02 gate check.\n\n"
                "# Findings\n\n"
                "The quarterly total came to 48350 dirhams across three regions.\n"
                "The largest single contributor was the Northern region.\n\n"
                "# Next steps\n\n"
                "Nothing here is real. It exists so read_pdf has something honest to read."
            ),
        )
        print(f"  wrote {result['file']}: {result['pages']} page(s), {result['size_kb']} KB")
        check("write_pdf created a file", (data_dir() / PDF_NAME).is_file())
    except Exception as exc:  # noqa: BLE001
        bad("write_pdf", repr(exc))

    # ---- read_pdf -----------------------------------------------------
    step("read_pdf")
    try:
        result = tools.read_pdf(PDF_NAME)
        text = result["text"]
        print(f"  {result['page_count']} page(s), {result['characters']} characters extracted")
        lines = [ln for ln in text.splitlines() if ln.strip() and not ln.startswith("---")]
        print(f"  first line of text: {lines[0][:60] if lines else '(none)'!r}")
        check("read_pdf found the number written into the PDF", "48350" in text,
              "round trip write -> read holds")
        check("read_pdf reports the page count", result["page_count"] >= 1)
    except Exception as exc:  # noqa: BLE001
        bad("read_pdf", repr(exc))

    # ---- write_excel (create) -----------------------------------------
    step("write_excel: create")
    try:
        result = tools.write_excel(
            XLSX_NAME,
            rows=[
                ["North", 21400],
                ["Central", 15200],
                ["South", 11750],
            ],
            headers=["Region", "Revenue"],
            sheet="Q1",
            mode="overwrite",
        )
        print(f"  {result['action']} {result['file']}, sheet {result['sheet']}, now {result['total_rows_now']} rows")
        check("write_excel created the workbook", (data_dir() / XLSX_NAME).is_file())
        check("header plus three data rows", result["total_rows_now"] == 4,
              f"got {result['total_rows_now']}")
    except Exception as exc:  # noqa: BLE001
        bad("write_excel create", repr(exc))

    # ---- write_excel (append, including a formula) ---------------------
    step("write_excel: append a row and a live formula")
    try:
        result = tools.write_excel(
            XLSX_NAME,
            rows=[["East", 9300], ["TOTAL", "=SUM(B2:B5)"]],
            sheet="Q1",
            mode="append",
        )
        print(f"  {result['action']} {result['file']}, wrote {result['rows_written']} rows "
              f"starting at row {result['started_at_row']}")
        check("append grew the sheet to 6 rows", result["total_rows_now"] == 6,
              f"got {result['total_rows_now']}")
    except Exception as exc:  # noqa: BLE001
        bad("write_excel append", repr(exc))

    # ---- read_excel ----------------------------------------------------
    step("read_excel")
    try:
        result = tools.read_excel(XLSX_NAME)
        print(f"  sheet {result['sheet']!r} of {result['sheets_available']}, "
              f"{result['total_rows']} rows")
        for row in result["rows"]:
            print(f"    {row}")
        check("header row read back correctly", result["likely_header"] == ["Region", "Revenue"],
              f"got {result['likely_header']}")
        check("appended row is present", any(r and r[0] == "East" for r in result["rows"]))
        print("\n  Note: the TOTAL cell reads as None here. That is correct, not a bug.")
        print("  openpyxl reads cached formula results, and a file Excel has never")
        print("  opened has no cached value yet. Open it in Excel once and it fills in.")
    except Exception as exc:  # noqa: BLE001
        bad("read_excel", repr(exc))

    # ---- list_files ----------------------------------------------------
    step("list_files")
    try:
        result = tools.list_files()
        for entry in result["files"]:
            print(f"    {entry['name']:<28} {entry['size_kb']:>7} KB   {entry['modified']}")
        names = {e["name"] for e in result["files"]}
        check("both sample files are listed", {PDF_NAME, XLSX_NAME} <= names)
    except Exception as exc:  # noqa: BLE001
        bad("list_files", repr(exc))

    # ---- safety --------------------------------------------------------
    step("safety: paths outside the data folder are refused")
    for attempt in ["../secrets.xlsx", "..\\..\\Windows\\System32\\drivers\\etc\\hosts"]:
        try:
            tools.read_pdf(attempt)
            bad(f"refused {attempt!r}", "it was NOT refused")
        except tools.ToolError as exc:
            msg = str(exc)
            if "outside the data folder" in msg:
                ok(f"refused {attempt!r}")
            else:
                # rejected for another reason (no such file) is weaker but not a breach
                ok(f"rejected {attempt!r}", f"({msg[:40]}...)")
        except Exception as exc:  # noqa: BLE001
            bad(f"refused {attempt!r}", repr(exc))

    step("missing files produce a message the model can act on")
    try:
        tools.read_excel("does_not_exist.xlsx")
        bad("missing file", "no error raised")
    except tools.ToolError as exc:
        print(f"  ToolError: {exc}")
        ok("missing file raises ToolError with the available filenames")
    except Exception as exc:  # noqa: BLE001
        bad("missing file", f"wrong exception type: {exc!r}")

    # ---- summary -------------------------------------------------------
    step("Gate")
    print(f"  {len(passed)} passed, {len(failed)} failed")
    if failed:
        for name in failed:
            print(f"    FAILED: {name}")
        print("\n  Phase 02 does not pass yet. Paste this output back into the chat.\n")
        return 1
    print("\n  Phase 02 passes. The file tools do what they claim on real files.")
    print("  Nothing further to do here. The two samples this check just wrote are")
    print("  still in the data folder if you want to look at them by eye:")
    print(f"    {data_dir() / XLSX_NAME}")
    print(f"    {data_dir() / PDF_NAME}\n")
    return 0


if __name__ == "__main__":
# Gate scripts call the tool functions directly, with no HTTP request to say
# whose data this is, so they name a tenant themselves. BOOTSTRAP_TENANT is the
# one holding the data this install started with.
    with context.use_tenant(BOOTSTRAP_TENANT):
        sys.exit(main())
